  <script type="text/javascript" src="{{RootPath}}/lib/jasmine-core/jasmine.js"></script>
  <script type="text/javascript">
    // yes, really keep this here to keep us honest, but only for jasmine's own runner! [xw]
    undefined = "diz be undefined yo";
  </script>

  <script type="text/javascript" src="{{RootPath}}/src/html/HtmlReporterHelpers.js"></script>
  <script type="text/javascript" src="{{RootPath}}/src/html/HtmlReporter.js"></script>
  <script type="text/javascript" src="{{RootPath}}/src/html/HtmlReporterHelpers.js"></script>
  <script type="text/javascript" src="{{RootPath}}/src/html/ReporterView.js"></script>
  <script type="text/javascript" src="{{RootPath}}/src/html/SpecView.js"></script>
  <script type="text/javascript" src="{{RootPath}}/src/html/SuiteView.js"></script>
  <script type="text/javascript" src="{{RootPath}}/src/html/TrivialReporter.js"></script>
  <script type="text/javascript" src="{{RootPath}}/src/console/ConsoleReporter.js"></script>
